apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: growth-quotient-ingestion
build:
  googleCloudBuild:
    projectId: null
  artifacts:
  - image: growth-quotient-ingestion
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s.yaml
