apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: growth-quotient-ingestion
build:
  artifacts:
    - image: growth-quotient-ingestion
      context: growth-quotient-ingestion
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - growth-quotient-ingestion/k8s.yaml
